export const tasks = [
  {
    title: 'Reading Books',
    date: new Date(),
    startTime: '10:00:00',
    category: 'reading',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
    status: 'new',
  },
  {
    title: 'Editing Audio',
    date: new Date(),
    startTime: '10:00:00',
    category: 'listening',
    workingSession: 3,
    longBreak: 15,
    shortBreak: 5,
    status: 'new',
  },
  {
    title: 'Learning Programming',
    date: new Date(),
    startTime: '10:00:00',
    category: 'learning',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
    status: 'new',
  },
  {
    title: 'Dumbbell Exercise',
    date: new Date(),
    startTime: '10:00:00',
    category: 'exercice',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
    status: 'new',
  },
  {
    title: 'Tech Exploration',
    date: new Date(),
    startTime: '10:00:00',
    category: 'tech',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
    status: 'new',
  },
  {
    title: 'Meditation',
    date: new Date(),
    startTime: '10:00:00',
    category: 'meditation',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
    status: 'new',
  },
  {
    title: 'Running',
    date: new Date(),
    startTime: '10:00:00',
    category: 'running',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
    status: 'new',
  },
  {
    title: 'Work',
    date: new Date(),
    startTime: '10:00:00',
    category: 'working',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
    status: 'new',
  },
  {
    title: 'Write blog',
    date: new Date(),
    startTime: '10:00:00',
    category: 'writing',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
    status: 'new',
  },
];
