export const tasks = [
  {
    title: 'Reading Books',
    date: new Date(),
    startTime: '10:00:00',
    category: 'read',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
  },
  {
    title: 'Editing Audio',
    date: new Date(),
    startTime: '10:00:00',
    category: 'listen',
    workingSession: 3,
    longBreak: 15,
    shortBreak: 5,
  },
  {
    title: 'Learning Programming',
    date: new Date(),
    startTime: '10:00:00',
    category: 'reading',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
  },
  {
    title: 'Dumbbell Exercise',
    date: new Date(),
    startTime: '10:00:00',
    category: 'reading',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
  },
  {
    title: 'Tech Exploration',
    date: new Date(),
    startTime: '10:00:00',
    category: 'reading',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
  },
  {
    title: 'Meditation',
    date: new Date(),
    startTime: '10:00:00',
    category: 'reading',
    workingSession: 2,
    longBreak: 15,
    shortBreak: 5,
  },
];
