export default {
  StartScreen: 'StartScreen',
  AppBottomTab: 'AppBottomTab',
  Statistics: 'Statistics',
  Home: 'Home',
  Profile: 'Profile',
  TodayTask: 'TodayTask',
  Task: 'Task',
  StartUp: 'StartUp',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  Login: 'Login',
  LoginWithPass: 'LoginWithPass',
  FillProfile: 'FillProfile',
  ForgotPass: 'ForgotPass',
  Notification: 'Notification',
  NewScope: 'NewScope',
};
